ONS-SST/cis_households

.bumpversion.cfg
CONTRIBUTING.md
setup.py

Added dev requirement, `bumpversion` config and documentation for use

565 Add bump2version for release versioning

---

cishouseholds/derive.py

Addresses CISDP-656 D11.
No tests as a simple function using just pyspark functions.

656 derive uniform value

---

.gitignore
cishouseholds/derive.py
tests/derive/test_derive_regex_match.py

649 regex match

---

cishouseholds/derive.py
tests/derive/test_assign_from_lookup.py
tests/derive/test_derive_from_list.py

Add two functions to handle the requirements for D10

660 map derive col

---

cishouseholds/derive.py
tests/derive/test_assign_consent_code.py

Still requires docstring, discussion and review.

Derive consent code function

---

cishouseholds/pipeline/bloods delta_ETL.py
cishouseholds/pipeline/calculate_survey_weights.py
cishouseholds/pipeline/sample_delta_ETL.py
cishouseholds/pipeline/survey_responses_voyager_2_ETL.py
cishouseholds/pipeline/swab_delta_ETL.py

High level entrypoint functions for adding calls to ETL functions.
Extract functions will expect a path to an input file.
Transform and load functions will expect pyspark dataframes.

Add entrypoint functions for core delta files

---

cishouseholds/pipeline/sample_delta_ETL.py
tests/pipeline/sample_delta_ETL/test_calculate_design_weights.py
tests/pipeline/sample_delta_ETL/test_edit_sample_file.py
tests/pipeline/test_calculate_design_weights.py

Adds two functions:
* edit_sample_file
* calculate_design_weights
Together, these allow calculation of design weights for a new sample delta.
Broke from standard naming, as the function has a very specific use case and specific names are more informative.

749 Add functions to calculate sample design weights

---

cishouseholds/edit.py
tests/edit/test_column_map.py

Added function to assign values based on map of existing column values. Tested for type variety.

746 column mapping edit

---

cishouseholds/filter.py

Internal pyspark methods only.
Added function to filter rows when all specified columns are missing.

Added filter for null variables function

---

cishouseholds/filter.py
tests/filter/test_filter_duplicates_time_and_threshold.py

Added function to perform filter 5.

754 filter duplicates time and float thresholds

---

cishouseholds/impute.py
tests/impute/test_impute_wrapper.py

Wrapper function used to call the various underlying imputation functions - adding flags and method names.

798 Added imputation wrapper function

---

cishouseholds/merge.py
tests/merge/test_derive_count_of_occurrences_column.py
tests/merge/test_derive_unique_identifier_column.py
tests/merge/test_join_dataframes.py

862 apply outer join

---

cishouseholds/merge.py
tests/merge/test_absolute_offset.py

Added absolute offset function for interval calculation.
Standard derive style function.

875 absolute offset

---

cishouseholds/merge.py
tests/merge/test_assign_merge_process_group_flag.py

Flag for filtering records to merge

876 Add assign_merge_process_group_flag with test

---

cishouseholds/merge.py
tests/merge/test_many_to_one_bloods_flags.py

new function for many-to-one-bloods matches

---

cishouseholds/impute.py

simplified and more generalised imputation

---

cishouseholds/impute.py

Standardise imputation inputs for wrapper

---

cishouseholds/validate.py
tests/validate/test_validate_merge_logic.py

819 - Basic merge logic validation

---

cishouseholds/weights.py
tests/weights/test_household_design_weights.py

894-household_populations_for_dweights

---

cishouseholds/edit.py
tests/edit/test_convert_columns_to_timestamps.py

Add function to convert strings to timestamps given a column:format map.
Needs: function implemented in pipeline.

990 Fix Schema For V2

---

cishouseholds/derive.py

CISDP-1013

---

cishouseholds/edit.py
cishouseholds/pipeline/Book1.csv
tests/edit/test_clean_postcode.py
tests/edit/test_update_from_csv_lookup.py

Cisdp-1002 clean postcode variable

---

cishouseholds/derive.py
cishouseholds/edit.py
tests/edit/test_split_columns_by_county.py

Cisdp 969 School year country columns

---

cishouseholds/edit.py

Change regex pattern to raw strings to resolve warnings

---

cishouseholds/extract.py
cishouseholds/pipeline/ETL_scripts.py
cishouseholds/pipeline/blood_delta_ETL.py
cishouseholds/pipeline/load.py
cishouseholds/pipeline/run.py
cishouseholds/pipeline/survey_responses_version_0_ETL.py
cishouseholds/pipeline/survey_responses_version_1_ETL.py
cishouseholds/pipeline/survey_responses_version_2_ETL.py
cishouseholds/pipeline/swab_delta_ETL.py

Refactor and apply read by date function in ETL stages

---

cishouseholds/pipeline/historical_blood_ETL.py
cishouseholds/pipeline/merge_process.py

Join on lab barcodes in now Null safe, so data are joined when no lab barcode is present

1186 Fix join of additional columns after merge

---

cishouseholds/extract.py
cishouseholds/pipeline/run.py
cishouseholds/pipeline/swab_delta_ETL.py

1190 swab date fix

---

cishouseholds/derive.py
cishouseholds/pipeline/ETL_scripts.py
cishouseholds/pipeline/blood_delta_ETL.py
cishouseholds/pipeline/historical_blood_ETL.py
cishouseholds/pipeline/run.py
cishouseholds/pipeline/survey_responses_version_0_ETL.py
cishouseholds/pipeline/survey_responses_version_1_ETL.py
cishouseholds/pipeline/survey_responses_version_2_ETL.py
cishouseholds/pipeline/swab_delta_ETL.py
tests/pipeline/test_blood_deltas.py
tests/pipeline/test_blood_deltas/processed_blood_data_regression.yml
tests/pipeline/test_blood_deltas/processed_blood_schema_regression.yml
tests/pipeline/test_historical_blood.py
tests/pipeline/test_historical_blood/processed_historical_blood_data_regression.yml
tests/pipeline/test_historical_blood/processed_historical_blood_schema_regression.yml
tests/pipeline/test_survey_responses_version_0.py
tests/pipeline/test_survey_responses_version_0/processed_responses_v0_data_regression.yml
tests/pipeline/test_survey_responses_version_0/processed_responses_v0_schema_regression.yml
tests/pipeline/test_survey_responses_version_1.py
tests/pipeline/test_survey_responses_version_1/processed_responses_v1_data_regression.yml
tests/pipeline/test_survey_responses_version_1/processed_responses_v1_schema_regression.yml
tests/pipeline/test_survey_responses_version_2.py
tests/pipeline/test_survey_responses_version_2/processed_responses_v2_data_regression.yml
tests/pipeline/test_survey_responses_version_2/processed_responses_v2_schema_regression.yml
tests/pipeline/test_swab_deltas.py

Refactor input file transformation and integration tests

---

cishouseholds/merge.py
cishouseholds/pipeline/merge_antibody_swab_ETL.py
tests/merge/test_join_assayed_bloods.py
tests/merge/test_null_safe_join.py

Fix outer blood join common columns

---

cishouseholds/derive.py
tests/derive/test_assign_proportion_column.py

CISDP-1172

---

cishouseholds/merge.py
cishouseholds/pipeline/merge_antibody_swab_ETL.py
cishouseholds/pipeline/merge_process.py
cishouseholds/pipeline/survey_responses_version_2_ETL.py
cishouseholds/pipeline/swab_delta_ETL.py
conftest.py
tests/pipeline/test_survey_responses_version_0/processed_responses_v0_data_regression.yml
tests/pipeline/test_survey_responses_version_1/processed_responses_v1_data_regression.yml
tests/pipeline/test_survey_responses_version_2/processed_responses_v2_data_regression.yml
tests/pipeline/test_swab_deltas/processed_swab_data_regression.yml
tests/pipeline/test_swab_deltas/processed_swab_schema_regression.yml

Add addition fields to unique IDs
Deduplicate blood and survey response records before merge

1217 Fix duplicate unique ID's before merge

---

dummy_data_generation/generate_data.py
dummy_data_generation/schemas.py

1159 Add NIMS dummy data table

---

cishouseholds/pipeline/generate_outputs.py
cishouseholds/pipeline/input_variable_names.py
cishouseholds/pipeline/post_merge_processing.py

1160 Add stage to join vaccination data to participants

---

cishouseholds/derive.py
cishouseholds/pipeline/survey_responses_version_2_ETL.py
tests/derive/test_assign_first_visit.py
tests/derive/test_assign_last_visit.py

CISDP-1282/3

---

cishouseholds/pipeline/survey_responses_version_2_ETL.py

CISDP-1277

---

cishouseholds/pipeline/generate_outputs.py
cishouseholds/pipeline/input_file_processing.py

amended generate_outputs

---

cishouseholds/pipeline/blood_delta_ETL.py
tests/pipeline/test_blood_deltas/processed_blood_data_regression.yml
tests/pipeline/test_blood_deltas/processed_blood_schema_regression.yml

1360 add variable to bloods etl

---

cishouseholds/extract.py

1361 Move latest_only file selection to after errored files are removed

---

cishouseholds/pipeline/merge_process.py

CISDP-1221-refactored merge validation to act on unioned df

---

cishouseholds/pipeline/generate_outputs.py
cishouseholds/pipeline/survey_responses_version_2_ETL.py
examples/pipeline_config.yaml

Ad-hoc changes to fix production pipeline

Update generate outputs and fix union-dependent transform

---

cishouseholds/derive.py
cishouseholds/pipeline/survey_responses_version_2_ETL.py

1015-contact_known_or_suspected_covid_type

---

cishouseholds/pipeline/load.py

1406 - Fix missing space in delete_tables SQL

---

cishouseholds/derive.py
cishouseholds/pipeline/output_variable_name_map.py
cishouseholds/pipeline/survey_responses_version_2_ETL.py
tests/derive/test_assign_column_to_date_string.py
tests/pipeline/test_survey_responses_version_0/processed_responses_v0_data_regression.yml
tests/pipeline/test_survey_responses_version_0/processed_responses_v0_schema_regression.yml
tests/pipeline/test_survey_responses_version_1/processed_responses_v1_data_regression.yml
tests/pipeline/test_survey_responses_version_1/processed_responses_v1_schema_regression.yml
tests/pipeline/test_survey_responses_version_2/processed_responses_v2_data_regression.yml
tests/pipeline/test_survey_responses_version_2/processed_responses_v2_schema_regression.yml

1431 Update string datetime format function

---

cishouseholds/impute.py
cishouseholds/pipeline/survey_responses_version_2_ETL.py
out.csv
tests/impute/test_fill_forward_work_columns.py

CISDP-1549 added work column fill forward

---

cishouseholds/impute.py
cishouseholds/pipeline/survey_responses_version_2_ETL.py
tests/pipeline/test_survey_responses_version_0/processed_responses_v0_data_regression.yml
tests/pipeline/test_survey_responses_version_1/processed_responses_v1_data_regression.yml
tests/pipeline/test_survey_responses_version_2/processed_responses_v2_data_regression.yml

CISDP-1537 added imputation for visit date

---

cishouseholds/pipeline/validation_ETL.py
cishouseholds/validate_class.py
tests/validate/test_sparkvalidate.py

1544-validations

---

cishouseholds/pipeline/output_variable_name_map.py
cishouseholds/pipeline/survey_responses_version_2_ETL.py
tests/pipeline/test_survey_responses_version_0/processed_responses_v0_data_regression.yml
tests/pipeline/test_survey_responses_version_0/processed_responses_v0_schema_regression.yml
tests/pipeline/test_survey_responses_version_1/processed_responses_v1_data_regression.yml
tests/pipeline/test_survey_responses_version_1/processed_responses_v1_schema_regression.yml
tests/pipeline/test_survey_responses_version_2/processed_responses_v2_data_regression.yml
tests/pipeline/test_survey_responses_version_2/processed_responses_v2_schema_regression.yml

1454 add iq barcode raw to file

---

cishouseholds/pipeline/validation_ETL.py

1548-validation

---

cishouseholds/edit.py
tests/edit/test_clean_barcode.py
tests/pipeline/test_blood_deltas/processed_blood_data_regression.yml
tests/pipeline/test_historical_blood/processed_historical_blood_data_regression.yml
tests/pipeline/test_survey_responses_version_0/processed_responses_v0_data_regression.yml
tests/pipeline/test_survey_responses_version_0/processed_responses_v0_schema_regression.yml
tests/pipeline/test_survey_responses_version_1/processed_responses_v1_data_regression.yml
tests/pipeline/test_survey_responses_version_2/processed_responses_v2_data_regression.yml
tests/pipeline/test_swab_deltas/processed_swab_data_regression.yml
tests/pipeline/test_swab_testkit_deltas/processed_swab_data_regression.yml

1572 - updated barcode cleaning

---

cishouseholds/pipeline/survey_responses_version_2_ETL.py

1730 -fixed fill forwrd work cols func calls

---

cishouseholds/pipeline/survey_responses_version_2_ETL.py

1740 Fix column name references

---

cishouseholds/impute.py
cishouseholds/pipeline/generate_outputs.py
tests/impute/test_fill_forward_work_columns.py

Fix fill forwards to use rolling window

---

cishouseholds/pipeline/weight_calibration.py

Add silencing of R import print statements

---

cishouseholds/pipeline/output_variable_name_map.py

1745 Fix output names for *_barcode_IQ variables

---

cishouseholds/edit.py
cishouseholds/pipeline/generate_outputs.py
examples/pipeline_config.yaml
tests/edit/test_update_from_csv_lookup.py

CISDP-1733 updated csv editing function

---

cishouseholds/pipeline/timestamp_map.py

1750 Fix datetime parsing formats for survey responses

---

cishouseholds/hdfs_utils.py
cishouseholds/pipeline/manifest.py

1752 Update manifest to use commandline md5sum

---

cishouseholds/impute.py
tests/impute/test_impute_visit_datetime.py
tests/pipeline/test_survey_responses_version_0/processed_responses_v0_data_regression.yml
tests/pipeline/test_survey_responses_version_1/processed_responses_v1_data_regression.yml
tests/pipeline/test_survey_responses_version_2/processed_responses_v2_data_regression.yml

amended impute_visit_datetime function and added test

---

cishouseholds/pipeline/category_map.py
cishouseholds/pipeline/survey_responses_version_2_ETL.py
tests/pipeline/test_survey_responses_version_0/processed_responses_v0_data_regression.yml
tests/pipeline/test_survey_responses_version_0/processed_responses_v0_schema_regression.yml
tests/pipeline/test_survey_responses_version_1/processed_responses_v1_data_regression.yml
tests/pipeline/test_survey_responses_version_1/processed_responses_v1_schema_regression.yml
tests/pipeline/test_survey_responses_version_2/processed_responses_v2_data_regression.yml
tests/pipeline/test_survey_responses_version_2/processed_responses_v2_schema_regression.yml

1762 Update self isolating mapping and remove school year before union

---

cishouseholds/edit.py
cishouseholds/pipeline/survey_responses_version_2_ETL.py
tests/edit/test_map_column_values_to_null.py

1770  - added conversion of did not attend to null

---

cishouseholds/pipeline/generate_outputs.py

Update filtering and reporting table references

---

cishouseholds/pipeline/survey_responses_version_2_ETL.py

 1832-amend_time_format

---

cishouseholds/pipeline/merge_antibody_swab_ETL.py

1417 1805 Add new stage to perform lookup based editing

---

cishouseholds/edit.py
cishouseholds/pipeline/survey_responses_version_2_ETL.py
tests/edit/test_clean_within_range.py

1842 - added range cleaning

---

cishouseholds/pipeline/survey_responses_version_2_ETL.py
tests/pipeline/test_survey_responses_version_2/processed_responses_v2_data_regression.yml

1858 Remove cleaning of work free text responses

---

cishouseholds/pipeline/category_map.py

1845 - added new category

---

cishouseholds/pipeline/merge_antibody_swab_ETL.py
cishouseholds/pipeline/survey_responses_version_0_ETL.py
cishouseholds/pipeline/survey_responses_version_2_ETL.py
tests/pipeline/test_survey_responses_version_0/processed_responses_v0_data_regression.yml
tests/pipeline/test_survey_responses_version_0/processed_responses_v0_schema_regression.yml
tests/pipeline/test_survey_responses_version_1/processed_responses_v1_data_regression.yml
tests/pipeline/test_survey_responses_version_1/processed_responses_v1_schema_regression.yml
tests/pipeline/test_survey_responses_version_2/processed_responses_v2_data_regression.yml
tests/pipeline/test_survey_responses_version_2/processed_responses_v2_schema_regression.yml

1855 1857 Rearrange union dependent transformations

---

cishouseholds/pipeline/survey_responses_version_1_ETL.py
cishouseholds/pipeline/survey_responses_version_2_ETL.py

removed mapping for work_status_v1 and function for work_status_combined

---

cishouseholds/pipeline/survey_responses_version_2_ETL.py

1873 - added mapping for work not from home

---

cishouseholds/edit.py
cishouseholds/pipeline/category_map.py
cishouseholds/pipeline/survey_responses_version_2_ETL.py
tests/edit/test_update_column_if_ref_in_list.py

1874 - update work location

---

cishouseholds/pipeline/survey_responses_version_2_ETL.py
tests/pipeline/test_survey_responses_version_1/processed_responses_v1_data_regression.yml
tests/pipeline/test_survey_responses_version_2/processed_responses_v2_data_regression.yml

1889 - converted outside country to upper

---

cishouseholds/edit.py
cishouseholds/pipeline/category_map.py
tests/edit/test_times_count_last_XX_days.py
tests/pipeline/test_survey_responses_version_2/processed_responses_v2_data_regression.yml
tests/pipeline/test_survey_responses_version_2/processed_responses_v2_schema_regression.yml

1898 - refactored count activitie

---

cishouseholds/pipeline/survey_responses_version_2_ETL.py

new values added to maps for work_status columns

---

cishouseholds/pipeline/pipeline_stages.py

updates to sheet names in excel reports to within 31 chars

---

cishouseholds/pipeline/survey_responses_version_2_ETL.py
tests/pipeline/test_survey_responses_version_0/processed_responses_v0_data_regression.yml
tests/pipeline/test_survey_responses_version_0/processed_responses_v0_schema_regression.yml
tests/pipeline/test_survey_responses_version_1/processed_responses_v1_data_regression.yml
tests/pipeline/test_survey_responses_version_1/processed_responses_v1_schema_regression.yml
tests/pipeline/test_survey_responses_version_2/processed_responses_v2_data_regression.yml
tests/pipeline/test_survey_responses_version_2/processed_responses_v2_schema_regression.yml

readded clean barcode

---

cishouseholds/pipeline/survey_responses_version_2_ETL.py

Updated work status dictionary

---

cishouseholds/pipeline/survey_responses_version_2_ETL.py
tests/pipeline/test_survey_responses_version_2/processed_responses_v2_schema_regression.yml

2054 Move vaccine fill forwards to only work on v2

---

cishouseholds/pipeline/generate_outputs.py
cishouseholds/pipeline/manifest.py
cishouseholds/pipeline/pipeline_stages.py

2052 Update writing function to allow sep and extension

---

cishouseholds/pipeline/pipeline_stages.py

recover-lookup_based_editing_stage

---

cishouseholds/validate_class.py
tests/validate/test_sparkvalidate.py

2053-warning_column-not-found

---

cishouseholds/pipeline/pipeline_stages.py

Refactor input processing to allow config params

---

cishouseholds/derive.py
tests/derive/test_assign_work_social_column.py
tests/pipeline/test_survey_responses_version_2/processed_responses_v2_data_regression.yml

fixed work social col

---

cishouseholds/derive.py
tests/derive/test_assign_people_in_household_count.py
tests/derive/test_assign_work_social_column.py

Updated logic to include participants with value of 0

---

cishouseholds/pipeline/survey_responses_version_2_ETL.py
tests/impute/test_fill_backwards_latest_version.py

BUG-fill_forward_backward

---

cishouseholds/derive.py
tests/derive/test_assign_people_in_household_count.py

reverted broken hh count and kept fix

---

cishouseholds/pipeline/survey_responses_version_2_ETL.py

commented out code for symptoms last 7 days

---

cishouseholds/impute.py
cishouseholds/pipeline/survey_responses_version_2_ETL.py
tests/impute/test_fill_forward_work_columns.py

Reverts ONS-SST/cis_households#386

Revert "BUG-fill_forward_backward-work_columns "

---

cishouseholds/impute.py
cishouseholds/pipeline/survey_responses_version_2_ETL.py
tests/impute/test_fill_forward_work_columns.py

Reverts ONS-SST/cis_households#390

Revert "Revert "BUG-fill_forward_backward-work_columns ""

---

cishouseholds/pipeline/survey_responses_version_2_ETL.py

bug-fill_forward

---

cishouseholds/pipeline/input_variable_names.py
cishouseholds/pipeline/survey_responses_version_2_ETL.py
tests/pipeline/test_survey_responses_version_2/processed_responses_v2_data_regression.yml
tests/pipeline/test_survey_responses_version_2/processed_responses_v2_schema_regression.yml

Fix work column name references

---

cishouseholds/impute.py
cishouseholds/pipeline/survey_responses_version_2_ETL.py
tests/impute/test_fill_forward_work_columns.py

2055-additional_work_status_v2

---

cishouseholds/edit.py
cishouseholds/expressions.py
cishouseholds/pipeline/survey_responses_version_0_ETL.py
cishouseholds/pipeline/survey_responses_version_1_ETL.py
cishouseholds/pipeline/survey_responses_version_2_ETL.py
tests/pipeline/test_survey_responses_version_0/processed_responses_v0_data_regression.yml
tests/pipeline/test_survey_responses_version_0/processed_responses_v0_schema_regression.yml
tests/pipeline/test_survey_responses_version_1/processed_responses_v1_data_regression.yml
tests/pipeline/test_survey_responses_version_1/processed_responses_v1_schema_regression.yml

Update work changed column before fill

---

cishouseholds/impute.py
tests/impute/test_fill_forward_work_columns.py

refactor-fill_forward_only_to_nulls

---

cishouseholds/pipeline/survey_responses_version_2_ETL.py

Fix for cohort to stop overwriting values with nulls

---

cishouseholds/pipeline/survey_responses_version_2_ETL.py

updated mapping for work_status_v2

---

cishouseholds/edit.py
cishouseholds/pipeline/survey_responses_version_2_ETL.py
tests/impute/test_fill_forward_work_columns.py
tests/pipeline/test_survey_responses_version_2/processed_responses_v2_data_regression.yml

2098-fill_forward_v2_as_v1_dataset01

---

cishouseholds/edit.py
cishouseholds/pipeline/survey_responses_version_1_ETL.py
cishouseholds/pipeline/survey_responses_version_2_ETL.py
tests/impute/test_fill_forward_work_columns.py
tests/pipeline/test_survey_responses_version_1/processed_responses_v1_data_regression.yml
tests/pipeline/test_survey_responses_version_1/processed_responses_v1_schema_regression.yml

Update work status v2 from work status v1

---

cishouseholds/pipeline/validation_schema.py

testKit field added to swab validation

---

cishouseholds/pipeline/pipeline_stages.py

update report stage to meet 31 chars for tab names

---

.pre-commit-config.yaml
cishouseholds/derive.py
cishouseholds/pipeline/category_map.py
cishouseholds/pipeline/survey_responses_version_0_ETL.py
cishouseholds/pipeline/survey_responses_version_2_ETL.py
tests/derive/test_assign_work_social_column.py
tests/pipeline/test_survey_responses_version_2/processed_responses_v2_data_regression.yml

2111 Fix work_social_care and work_health_care_v1_v2

---

cishouseholds/derive.py
cishouseholds/edit.py
cishouseholds/pipeline/input_file_stages.py
cishouseholds/pipeline/survey_responses_version_0_ETL.py
cishouseholds/pipeline/survey_responses_version_1_ETL.py
cishouseholds/pipeline/survey_responses_version_2_ETL.py
tests/derive/test_assign_work_health_care.py
tests/derive/test_assign_work_social_column.py
tests/pipeline/test_survey_responses_version_1/processed_responses_v1_data_regression.yml
tests/pipeline/test_survey_responses_version_1/processed_responses_v1_schema_regression.yml
tests/pipeline/test_survey_responses_version_2/processed_responses_v2_data_regression.yml
tests/pipeline/test_survey_responses_version_2/processed_responses_v2_schema_regression.yml

Fix work social care and health care derivations

---

cishouseholds/pipeline/pipeline_stages.py
cishouseholds/weights/extract.py
cishouseholds/weights/weights.py

2113 - refactored sample etl

---

cishouseholds/pipeline/category_map.py
cishouseholds/pipeline/survey_responses_version_2_ETL.py

Add category map for health care v0

---

cishouseholds/pipeline/pipeline_stages.py

2119 - refactored report stage to get names from conf

---

cishouseholds/derive.py
cishouseholds/expressions.py
cishouseholds/pipeline/pipeline_stages.py
cishouseholds/pipeline/survey_responses_version_2_ETL.py
tests/derive/test_assign_household_under_2_count.py
tests/pipeline/test_derive_people_in_household_count.py

2127-refactor-assign_hh_under_2_count

---

cishouseholds/pipeline/input_variable_names.py
cishouseholds/pipeline/validation_schema.py

2133 = modified validation schema for lookups

---

cishouseholds/edit.py
cishouseholds/pipeline/survey_responses_version_0_ETL.py
cishouseholds/pipeline/survey_responses_version_1_ETL.py
cishouseholds/pipeline/survey_responses_version_2_ETL.py
tests/pipeline/test_survey_responses_version_0/processed_responses_v0_data_regression.yml
tests/pipeline/test_survey_responses_version_0/processed_responses_v0_schema_regression.yml
tests/pipeline/test_survey_responses_version_1/processed_responses_v1_data_regression.yml
tests/pipeline/test_survey_responses_version_1/processed_responses_v1_schema_regression.yml
tests/pipeline/test_survey_responses_version_2/processed_responses_v2_data_regression.yml
tests/pipeline/test_survey_responses_version_2/processed_responses_v2_schema_regression.yml

Move barcode cleaning to be applied to v0 and v1 only

---

cishouseholds/pipeline/validation_schema.py

Fixing address column name issues

---

cishouseholds/weights/derive.py
cishouseholds/weights/weights.py

reordered funciton calls

---

cishouseholds/pipeline/input_file_processing.py

CISDP-2149added dataset verison input

---

cishouseholds/pipeline/input_file_processing.py
cishouseholds/pipeline/pipeline_stages.py

modified csv to table

---

cishouseholds/pipeline/input_variable_names.py
cishouseholds/pipeline/validation_schema.py

Small update to fix the error caused by lsoa11

---

cishouseholds/merge.py
cishouseholds/pipeline/R_pipeline_stages.py
cishouseholds/pipeline/load.py
cishouseholds/pipeline/merge_antibody_swab_ETL.py
cishouseholds/pipeline/pipeline_stages.py

2152/3 - removed config master write mode param

---

cishouseholds/pipeline/input_file_processing.py
cishouseholds/pipeline/pipeline_stages.py
cishouseholds/validate.py

2157 - made ready for testing

---

cishouseholds/pipeline/pipeline_stages.py

2147 - added report changes

---

cishouseholds/weights/weights.py
tests/weights/test_household_level_populations.py

2181 Deduplicate lookups before joining to addressbase

---

cishouseholds/weights/pre_calibration.py
cishouseholds/weights/weights.py
tests/weights/test_validate_design_weights.py

2182 - modified dweight validation to accept cis and country populations 

---

cishouseholds/derive.py
cishouseholds/edit.py
cishouseholds/weights/weights.py
tests/derive/test_assign_outer_postcode.py
tests/edit/test_clean_postcode.py
tests/pipeline/test_survey_responses_version_0/processed_responses_v0_data_regression.yml
tests/pipeline/test_survey_responses_version_1/processed_responses_v1_data_regression.yml
tests/pipeline/test_survey_responses_version_2/processed_responses_v2_data_regression.yml
tests/weights/test_household_level_populations.py

Clean postcodes for design weight stages

---

cishouseholds/extract.py
cishouseholds/pipeline/pipeline_stages.py
dummy_data_generation/generate_data.py

2187 - ran an unioned cis-digital

---

cishouseholds/derive.py

modified fake id creation

---

cishouseholds/extract.py
cishouseholds/pipeline/pipeline_stages.py
dummy_data_generation/generate_data.py
tests/validate/test_sparkvalidate.py

Cisdp 2187

---

cishouseholds/extract.py

fixed file date regex

---

cishouseholds/derive.py
cishouseholds/pipeline/post_merge_processing.py
cishouseholds/pipeline/survey_responses_version_2_ETL.py
tests/derive/test_assign_work_status_group.py
tests/pipeline/test_derive_people_in_household_count.py
tests/pipeline/test_impute_impute_key_columns.py

Derive columns needed for imputation

---

cishouseholds/pipeline/survey_responses_version_digital_ETL.py
tests/pipeline/test_survey_responses_version_digital/processed_responses_digital_data_regression.yml

2201 - added work from home derivation#

---

cishouseholds/weights/weights.py

2249 Fix design weight validation check

---

cishouseholds/pipeline/survey_responses_version_2_ETL.py

fixed main

---

cishouseholds/pipeline/pipeline_stages.py

updated tables to csv

---

cishouseholds/edit.py
tests/edit/test_update_column_in_time_window.py

2260 - added update value in time constraint

---

cishouseholds/pipeline/survey_responses_version_2_ETL.py

2262 Add cisd date vars to create_formatted_datetime_string_columns function

---

cishouseholds/weights/pre_calibration.py
cishouseholds/weights/weights.py
tests/weights/test_carry_forward_design_weights.py
tests/weights/test_dweights_precalibration_checkpoints.py

Fix design weight checks

---

cishouseholds/pipeline/survey_responses_version_1_ETL.py
cishouseholds/pipeline/survey_responses_version_2_ETL.py
cishouseholds/pipeline/survey_responses_version_digital_ETL.py
tests/pipeline/test_survey_responses_version_1/processed_responses_v1_schema_regression.yml
tests/pipeline/test_survey_responses_version_2/processed_responses_v2_schema_regression.yml
tests/pipeline/test_survey_responses_version_digital/processed_responses_digital_data_regression.yml
tests/pipeline/test_survey_responses_version_digital/processed_responses_digital_schema_regression.yml

Fix derivation of digital and V2 columns for digital changes. Involved moving code from V1/V2 to specific transformation functions. Also cleaned up some comments

2158 Fix self_isolating_reason derivation for digital

---

cishouseholds/pipeline/pipeline_stages.py
cishouseholds/pipeline/reporting.py
cishouseholds/pipeline/survey_responses_version_2_ETL.py
cishouseholds/pipeline/timestamp_map.py
tests/pipeline/test_survey_responses_version_digital/processed_responses_digital_data_regression.yml

2270 - removed digital references from union transforms

---

cishouseholds/weights/pre_calibration.py
cishouseholds/weights/weights.py
tests/weights/test_dweights_precalibration_checkpoints.py

Dropped swab consistency check and adjusting sum check rounding to 0d.p.

2274 Update design weight validation rules

---

cishouseholds/pipeline/high_level_transformations.py
tests/pipeline/test_survey_responses_version_digital/processed_responses_digital_data_regression.yml

2278 update dont_know_mapping_dict

---

cishouseholds/pipeline/high_level_transformations.py

Update digital_survey_collection_mode to reflect period of online form outage
- last changes requires cut off end time to 11:00

2260-updated_to_11

---

cishouseholds/pipeline/high_level_transformations.py
tests/pipeline/test_survey_responses_version_0/processed_responses_v0_schema_regression.yml
tests/pipeline/test_survey_responses_version_1/processed_responses_v1_schema_regression.yml
tests/pipeline/test_survey_responses_version_2/processed_responses_v2_schema_regression.yml
tests/pipeline/test_survey_responses_version_digital/processed_responses_digital_data_regression.yml
tests/pipeline/test_survey_responses_version_digital/processed_responses_digital_schema_regression.yml

moved from `transform_survey_responses_generic` to specific transformations transform_survey_responses_version_0_delta, transform_survey_responses_version_1_delta, transform_survey_responses_version_2_delta only,

2280-test_taken_edit_from_barcode

---

cishouseholds/pipeline/validation_calls.py
cishouseholds/validate_class.py

2180 Change validation to use file date and fixed operator

---

cishouseholds/pipeline/reporting.py

2167 - re implemented error ordering on report

---

cishouseholds/mapping.py

2258 - updated category map

---

cishouseholds/edit.py
cishouseholds/pipeline/input_file_processing.py
cishouseholds/pipeline/pipeline_stages.py
tests/edit/test_update_from_lookup_df.py

2289 - modified record interface

---

cishouseholds/pipeline/high_level_transformations.py

2287 - added null option work status digital with edu

---

cishouseholds/pipeline/high_level_transformations.py
dummy_data_generation/schemas.py
tests/pipeline/test_survey_responses_version_digital/processed_responses_digital_data_regression.yml
tests/pipeline/test_survey_responses_version_digital/processed_responses_digital_schema_regression.yml
tests/pipeline/test_union_dependent_transformations/processed_post_union_data_regression_data_regression.yml
tests/pipeline/test_union_dependent_transformations/processed_post_union_schema_regression_schema_regression.yml

2291 - updated mapping of work status v0

---

cishouseholds/weights/design_weights.py
tests/weights/test_dweights_precalibration_checkpoints.py

 2266 modify validate_design_weights() unit-test to use pytest.raise

---

cishouseholds/pipeline/pipeline_stages.py

fixed tables to csv filter

---

cishouseholds/pipeline/validation_calls.py
cishouseholds/validate_class.py

Allows two days of leeway, to account for older files being dated for previous day and some files including data from during the current day

2180 Update visit_datetime validation check

---

cishouseholds/pipeline/high_level_transformations.py
cishouseholds/pipeline/pipeline_stages.py
cishouseholds/pipeline/timestamp_map.py
cishouseholds/pipeline/validation_schema.py

2294 - added csv to table schema for imputed values and casted to type

---

cishouseholds/impute.py
cishouseholds/pipeline/high_level_transformations.py
tests/impute/test_fill_forward_work_columns.py

2319 Update fill forwards to allow limit on dataset version

---

cishouseholds/pipeline/high_level_transformations.py

2344 - added dont know mappings

---

cishouseholds/impute.py

Solves memory issues when imputing for a large number of records

2343 Remove broadcast in KNN imputation

---

cishouseholds/pipeline/validation_calls.py

2366 - added visit datetime validation

---

cishouseholds/impute.py
cishouseholds/pipeline/__init__.py
cishouseholds/pipeline/high_level_transformations.py
tests/impute/test_knn_imputation_for_date.py
tests/pipeline/test_impute_impute_key_columns.py

2388 - remade branch 2394

---

cishouseholds/pyspark_utils.py

2386 Spark session config changes

---

cishouseholds/pipeline/high_level_transformations.py
cishouseholds/pipeline/pipeline_stages.py
tests/pipeline/test_survey_responses_version_0/processed_responses_v0_data_regression.yml
tests/pipeline/test_survey_responses_version_0/processed_responses_v0_schema_regression.yml
tests/pipeline/test_survey_responses_version_1/processed_responses_v1_data_regression.yml
tests/pipeline/test_survey_responses_version_1/processed_responses_v1_schema_regression.yml
tests/pipeline/test_survey_responses_version_2/processed_responses_v2_data_regression.yml
tests/pipeline/test_survey_responses_version_2/processed_responses_v2_schema_regression.yml
tests/pipeline/test_survey_responses_version_digital/processed_responses_digital_data_regression.yml
tests/pipeline/test_survey_responses_version_digital/processed_responses_digital_schema_regression.yml

2396 - reran regressions

---

cishouseholds/pipeline/input_file_processing.py
cishouseholds/pipeline/pipeline_stages.py

2358 - added docstring for input file processing

---

tests/derive/test_assign_outer_postcode.py

2396 modified postcode test

---

cishouseholds/pipeline/high_level_transformations.py
cishouseholds/pipeline/input_file_stages.py
tests/pipeline/test_survey_responses_version_2/processed_responses_v2_schema_regression.yml
tests/pipeline/test_survey_responses_version_digital/processed_responses_digital_data_regression.yml
tests/pipeline/test_survey_responses_version_digital/processed_responses_digital_schema_regression.yml

2391 - added has been to digital

---

dummy_data_generation/schemas.py
tests/pipeline/test_survey_responses_version_2/processed_responses_v2_data_regression.yml
tests/pipeline/test_survey_responses_version_digital/processed_responses_digital_data_regression.yml

- change location from v2 to digital
- re-run regression test

2397 fix - change location of vaccination types from v2 to digital

---

cishouseholds/pipeline/run.py

2382 added date time when stages start

---

cishouseholds/pipeline/pipeline_stages.py

2400 - fixed duplicate soc df

---

cishouseholds/pipeline/timestamp_map.py

2436 - added form_start_datetime to timestamp_map

---

cishouseholds/pipeline/high_level_transformations.py
cishouseholds/pipeline/mapping.py

2414 - adding to mapping for consolidation error codes

---

cishouseholds/pipeline/high_level_transformations.py

2413-update to consolidation point error re-coding

---

cishouseholds/pipeline/high_level_transformations.py

2438 - fixed ageg bounds

---

cishouseholds/pipeline/pipeline_stages.py

2462 - fix typo

---

cishouseholds/pipeline/pipeline_stages.py

2465: added reclassify_work_variables into the pipeline

---

cishouseholds/pipeline/high_level_transformations.py

CISDP 1367 LOCF

---

cishouseholds/impute.py
cishouseholds/pipeline/high_level_transformations.py
cishouseholds/pipeline/regex_testing.py
tests/pipeline/test_union_dependent_transformations.py

2478 - revert for uat run

---

cishouseholds/pipeline/mapping.py

2475 adding mapping for visit_date_type

---

cishouseholds/pipeline/generate_outputs.py
cishouseholds/pipeline/high_level_transformations.py
cishouseholds/pipeline/pipeline_stages.py

fixed stratified sample and made generic

---

cishouseholds/impute.py
cishouseholds/pipeline/high_level_transformations.py
cishouseholds/pipeline/regex_testing.py
tests/pipeline/test_union_dependent_transformations.py

This reverts commit 5905e85a5d3a46eb6105b96e223755eb133e11db, restoring function for further UAT testing.

2490 - Revert 2478 (#740)

---

.github/workflows/pr_testing.yml
cishouseholds/derive.py

2537 - updated git testing workflows

---

cishouseholds/impute.py

2351 impute documentation review

---

cishouseholds/pipeline/pipeline_stages.py
cishouseholds/pipeline/reporting.py
tests/expressions/test_count_variable_option.py

soc code uncodeable count

---

cishouseholds/pipeline/mapping.py

updating mapping to align with stata labels for 1 variable

---

cishouseholds/pipeline/mapping.py
cishouseholds/pipeline/translate.py

2587 - updated welsh fixed text mapping

---

cishouseholds/pipeline/mapping.py
cishouseholds/pipeline/translate.py
cishouseholds/pipeline/validation_schema.py
dummy_data_generation/schemas.py
tests/pipeline/test_survey_responses_version_digital/processed_responses_digital_data_regression.yml
tests/pipeline/test_survey_responses_version_digital/processed_responses_digital_schema_regression.yml

2598 - new vaccine variable added to schema for spec 1.5

---

cishouseholds/pipeline/pipeline_stages.py
cishouseholds/pipeline/reporting.py
tests/expressions/test_count_variable_option.py

Cisdp 2454

---

cishouseholds/pipeline/high_level_transformations.py
tests/pipeline/test_survey_responses_version_2/processed_responses_v2_data_regression.yml
tests/pipeline/test_survey_responses_version_2/processed_responses_v2_schema_regression.yml

2633 - Added v2 _raw vaccine doses

---

cishouseholds/pipeline/generate_outputs.py
cishouseholds/pipeline/mapping.py
cishouseholds/pipeline/pipeline_stages.py

2629 - update mapping

---

cishouseholds/pipeline/generate_outputs.py
cishouseholds/pipeline/pipeline_stages.py
cishouseholds/pipeline/run.py

2638 - made regex lookup table optional

---

cishouseholds/derive.py
cishouseholds/pipeline/high_level_transformations.py
cishouseholds/pipeline/pipeline_stages.py

2649 - fix regex union logic and add dynamic repartitions

---

cishouseholds/pipeline/pipeline_stages.py

2648 - stage fixed

---

cishouseholds/derive.py
cishouseholds/expressions.py
cishouseholds/pipeline/high_level_transformations.py
cishouseholds/pipeline/pipeline_stages.py

2664 - fix skewed partitions in soc and regex stages

---

cishouseholds/impute.py

2677 - optimise for Spark plan implementation

---

cishouseholds/merge.py
cishouseholds/pipeline/high_level_transformations.py
cishouseholds/pipeline/pipeline_stages.py
tests/pipeline/test_transform_cis_soc_data.py

2669 - refactored lookup table joins

---

cishouseholds/pipeline/high_level_transformations.py
dummy_data_generation/schemas.py
tests/pipeline/test_survey_responses_version_digital/processed_responses_digital_data_regression.yml
tests/pipeline/test_survey_responses_version_digital/processed_responses_digital_schema_regression.yml

2711 - update CIS-D ethnicity mapping logic

---

cishouseholds/pipeline/pipeline_stages.py

2346 - update pipeline_stages docstrings

---

cishouseholds/pipeline/high_level_transformations.py
cishouseholds/pipeline/mapping.py
tests/pipeline/test_survey_responses_version_digital/processed_responses_digital_data_regression.yml

2730 - Updated mapping to account for all options of vaccine type

---

cishouseholds/derive.py
tests/derive/test_assign_datetime_from_coalesced_columns_and_log_source.py

2753 - visit_datetime fix

---

cishouseholds/pipeline/pipeline_stages.py

2772 - fix join_lookup_df in unjoinable_values loop

---

cishouseholds/pipeline/load.py
cishouseholds/pipeline/pipeline_stages.py

2766 - add table_to_table stage and modify extract_from_table

---

cishouseholds/edit.py
tests/edit/test_replace_sample_barcode.py

Cisdp 2776 - temporary hard date applied for replace_sample_barcode

---

cishouseholds/pipeline/high_level_transformations.py

2777 - remove regex_derived_job_sector from regex output

---

tests/pipeline/test_union_dependent_transformations.py

2761 - union dependent transforms test refactor

---

cishouseholds/edit.py
cishouseholds/impute.py
cishouseholds/pipeline/high_level_transformations.py
cishouseholds/pipeline/pipeline_stages.py
cishouseholds/pipeline/run.py
cishouseholds/validate.py

2778 - fixed event dates, soc lookup

---

cishouseholds/impute.py

2749 - added check for ref event date before visit date

---

cishouseholds/impute.py
tests/impute/test_fill_forward_event.py

2762 - fixed event fill forward

---

cishouseholds/pipeline/pipeline_stages.py
cishouseholds/predicition_checker_class.py

2765 - Prediction checker

---

.github/workflows/pr_testing.yml
cishouseholds/derive.py
tests/pipeline/test_survey_responses_version_digital/processed_responses_digital_data_regression.yml

2740 - update visit_datetime logic

---

cishouseholds/impute.py

redo of CISDP-2795

---

cishouseholds/pipeline/mapping.py

2813 - addition to mapping for visit_date_type

---

cishouseholds/pipeline/load.py
cishouseholds/pipeline/logging.py
cishouseholds/pipeline/run.py

2824 - added table length logging

---

cishouseholds/derive.py
tests/pipeline/test_survey_responses_version_digital/processed_responses_digital_data_regression.yml

2740 patch - correction to minimum date bound

---

cishouseholds/edit.py
tests/edit/test_replace_sample_barcode.py

CISDP2832 -update replace barcode logic & test

---

cishouseholds/pipeline/high_level_transformations.py

2807 corrected value map for visit_number

---

cishouseholds/pipeline/pipeline_stages.py

2820 - removed references to rural_urban_classification_11

---

cishouseholds/pipeline/high_level_transformations.py

update days_since_enrolment calculation

---

cishouseholds/pipeline/high_level_transformations.py

2805 - removed fill forwards vaccine cols

---

cishouseholds/pipeline/high_level_transformations.py
tests/pipeline/test_survey_responses_version_0/processed_responses_v0_data_regression.yml
tests/pipeline/test_survey_responses_version_0/processed_responses_v0_schema_regression.yml
tests/pipeline/test_survey_responses_version_2/processed_responses_v2_data_regression.yml
tests/pipeline/test_survey_responses_version_2/processed_responses_v2_schema_regression.yml
tests/pipeline/test_survey_responses_version_digital/processed_responses_digital_data_regression.yml
tests/pipeline/test_survey_responses_version_digital/processed_responses_digital_schema_regression.yml

2838 - put back work_main_job_changed update pre prove

---

cishouseholds/pipeline/high_level_transformations.py

2834 - added think_had_covid_any to detail cols

---

cishouseholds/pipeline/high_level_transformations.py
tests/pipeline/test_participant_extract_version_digital/processed_participants_digital_data_regression.yml
tests/pipeline/test_participant_extract_version_digital/processed_participants_digital_schema_regression.yml

2861 - add ordered_household_id to participant processing

---

cishouseholds/pipeline/high_level_transformations.py
tests/pipeline/test_survey_responses_version_digital/processed_responses_digital_data_regression.yml

accounts for case sensitive translation map

2858 - add value to dont_know_mapping_dict

---

cishouseholds/pipeline/high_level_transformations.py

2835 - function call for A25 logic for other_covid_infection_test 

---

cishouseholds/derive.py
cishouseholds/pipeline/high_level_transformations.py
tests/derive/test_assign_last_non_null_value_from_col_list.py

2855 - function to sort and assign value based on input cols for deriving covid_contact_days_since

---

cishouseholds/derive.py
cishouseholds/pipeline/input_file_processing.py

2864 - added file name for excel input stage

---

cishouseholds/pipeline/high_level_transformations.py
cishouseholds/pipeline/pipeline_stages.py
tests/pipeline/test_participant_extract_version_digital/processed_participants_digital_data_regression.yml
tests/pipeline/test_participant_extract_version_digital/processed_participants_digital_schema_regression.yml

2861 - fix ordered household id for participant extract 

---

cishouseholds/edit.py
cishouseholds/pipeline/high_level_transformations.py
tests/edit/test_fuzzy_update.py

CISDIP 2881 - A26 fuzzy matching logic

---

cishouseholds/pipeline/high_level_transformations.py
cishouseholds/pipeline/pipeline_stages.py

2847 - removed specific join_lookup stages

---

cishouseholds/pipeline/mapping.py

Updated work_patient_facing_now mapping

---

cishouseholds/pipeline/pipeline_stages.py

2895 - limit vaccine report to 50k rows

---

cishouseholds/pipeline/post_union_transformations.py
cishouseholds/pipeline/pre_union_transformations.py
tests/pipeline/test_survey_responses_version_0/processed_responses_v0_data_regression.yml
tests/pipeline/test_survey_responses_version_0/processed_responses_v0_schema_regression.yml
tests/pipeline/test_survey_responses_version_1/processed_responses_v1_data_regression.yml
tests/pipeline/test_survey_responses_version_1/processed_responses_v1_schema_regression.yml
tests/pipeline/test_survey_responses_version_2/processed_responses_v2_data_regression.yml
tests/pipeline/test_survey_responses_version_2/processed_responses_v2_schema_regression.yml
tests/pipeline/test_survey_responses_version_digital/processed_responses_digital_data_regression.yml
tests/pipeline/test_survey_responses_version_digital/processed_responses_digital_schema_regression.yml

2846 - moved work main job title/roll concat

---

cishouseholds/edit.py
cishouseholds/pipeline/load.py
cishouseholds/pipeline/logging.py
cishouseholds/pipeline/pipeline_stages.py
cishouseholds/pipeline/pre_union_transformations.py
cishouseholds/pipeline/run.py

2930 - moved length logging to seperate function

---

cishouseholds/pipeline/post_union_transformations.py

2945 - move known and suspected contact prior to a25 a26

---

cishouseholds/pipeline/job_transformations.py
cishouseholds/pipeline/version_specific_processing/v1_transformations.py
tests/pipeline/test_survey_responses_version_1/processed_responses_v1_data_regression.yml
tests/pipeline/test_survey_responses_version_1/processed_responses_v1_schema_regression.yml

2963 - work_main_job_changed logic update for prod comparison

---

.idea/workspace.xml
cishouseholds/pipeline/job_transformations.py

2964 - added repopulate function

---

cishouseholds/edit.py
cishouseholds/pipeline/covid_event_transformations.py
tests/edit/test_update_think_have_covid_symptom_any.py

2947 - update think_have_covid_symptom_any logic

---

.idea/workspace.xml
cishouseholds/pipeline/job_transformations.py

2974 - moved work status transforms back into main workflow

---

.idea/workspace.xml
cishouseholds/expressions.py
cishouseholds/pipeline/version_specific_processing/digital_transformations.py
tests/edit/test_edit_to_sum_or_max_value.py
tests/pipeline/test_survey_responses_version_digital/processed_responses_digital_data_regression.yml
tests/pipeline/test_survey_responses_version_digital/processed_responses_digital_schema_regression.yml

2976 - edited sum or max to work cast values to integer

---

cishouseholds/pipeline/pipeline_stages.py

2992 - create formatted datetime string call added

---

cishouseholds/pipeline/covid_event_transformations.py
cishouseholds/pipeline/job_transformations.py
cishouseholds/pipeline/lookup_and_regex_transformations.py
cishouseholds/pipeline/post_union_processing.py

CISDP-2304 adding original work cols and think_had_cghfevamn

---

cishouseholds/pipeline/load.py

3080 - revert update_table call for static log files

---

cishouseholds/pipeline/version_specific_processing/phm_transformations.py

3047-added derived variables

---

cishouseholds/pipeline/mapping.py

3004 added aged_16_or_over variable

---

cishouseholds/pipeline/version_specific_processing/phm_transformations.py
dummy_data_generation/schemas.py

3042 - added transport_shared_outside_household_last_28_days

---

cishouseholds/pipeline/mapping.py

2980 adding mapping for time_indoor_exercise_last_28_days

---

cishouseholds/pipeline/version_specific_processing/phm_transformations.py

2978 added on to existing mapping

---

cishouseholds/phm/high_level_phm_transformations.py
cishouseholds/pipeline/version_specific_processing/phm_transformations.py
tests/pipeline/test_survey_responses_version_phm.py
tests/pipeline/test_survey_responses_version_phm/processed_responses_phm_data_regression.yml

3048 - update think_had_covid_any_symptoms derivation

---

.idea/workspace.xml
cishouseholds/pipeline/mapping.py
cishouseholds/pipeline/post_union_processing.py

3035/3058 - PHM updated mapping

---

cishouseholds/pipeline/post_union_processing.py

variable name correction for test_results 

---

cishouseholds/pipeline/covid_event_transformations.py
cishouseholds/pipeline/mapping.py
cishouseholds/pipeline/version_specific_processing/digital_transformations.py
tests/pipeline/test_survey_responses_version_digital/processed_responses_digital_data_regression.yml

CISDP-3098 fixes for contact_known_or_suspected vars and mapping updates

---

cishouseholds/pipeline/post_union_processing.py
cishouseholds/pipeline/version_specific_processing/digital_transformations.py
tests/pipeline/test_survey_responses_version_digital/processed_responses_digital_data_regression.yml
tests/pipeline/test_survey_responses_version_digital/processed_responses_digital_schema_regression.yml

3156 correcting other_covid_infection_test_results mapping across post union and digital processing

---

.idea/workspace.xml
cishouseholds/pipeline/version_specific_processing/digital_transformations.py

3163 - moved edit auto complete call

---

tests/pipeline/test_clean_covid_swab.py

3170 take 2 - updating test for test_clean_covid_swab

---

cishouseholds/pipeline/mapping.py
cishouseholds/pipeline/visit_transformations.py
tests/pipeline/test_survey_responses_version_phm/processed_responses_phm_data_regression.yml

3170 - fix to week of enrolment for SP requirement

---

cishouseholds/derive.py
cishouseholds/pipeline/timestamp_map.py
dummy_data_generation/schemas.py
tests/derive/test_assign_datetime_from_combined_columns.py
tests/pipeline/test_survey_responses_version_phm/processed_responses_phm_data_regression.yml
tests/pipeline/test_survey_responses_version_phm/processed_responses_phm_schema_regression.yml

3178 - fix phm regression unit tests

---

cishouseholds/pipeline/load.py
cishouseholds/pipeline/pipeline_stages.py
tests/pipeline/test_survey_responses_version_phm/processed_responses_phm_data_regression.yml

adds in alternative database as a parameters for extract_from_table (and other functions upstream) so that tables from other databases (not covserolink)  can be used 

CISDP-3169 adding parameter for alternative database option

---

cishouseholds/derive.py
cishouseholds/edit.py
cishouseholds/expressions.py
cishouseholds/pipeline/vaccine_transformations.py
tests/derive/test_assign_valid_order.py

Recreated due to workflow issues.

2935 - update valid_order function implementation

---

.github/workflows/bump_UAT_version.yml
.github/workflows/docs.yml
.github/workflows/main.yml
.github/workflows/pr_testing.yml

3188 - update workflow from v2 to v3

---

.idea/workspace.xml
cishouseholds/edit.py
cishouseholds/phm/reporting_class.py
cishouseholds/pipeline/input_file_processing.py
cishouseholds/pipeline/pipeline_stages.py
cishouseholds/pyspark_utils.py
cishouseholds/validate.py

3181 - added a validation function for processed files

---

cishouseholds/phm/json_decode.py
cishouseholds/pipeline/mapping.py
cishouseholds/pipeline/validation_schema.py
tests/derive/test_map_options_to_bool_columns.py
tests/pipeline/test_survey_responses_version_phm/processed_responses_phm_data_regression.yml
tests/pipeline/test_survey_responses_version_phm/processed_responses_phm_schema_regression.yml

CISDP- 2967 updating json decoder to read in test file

---

cishouseholds/pipeline/timestamp_map.py
tests/pipeline/test_survey_responses_version_phm/processed_responses_phm_data_regression.yml
tests/pipeline/test_survey_responses_version_phm/processed_responses_phm_schema_regression.yml

3199 - added variables to phm_datetime_map

---

cishouseholds/derive.py
cishouseholds/pipeline/load.py
cishouseholds/pipeline/pipeline_stages.py

CISDP-3194 adding functionality to get_full_table_name to read latest table as option, if table has YYYYMMDD as suffix

---

cishouseholds/phm/reporting_class.py
cishouseholds/pipeline/pipeline_stages.py

3210 - Fix implementation of phm and validation reports

---

cishouseholds/pipeline/mapping.py
dummy_data_generation/schemas.py
tests/pipeline/test_survey_responses_version_phm/processed_responses_phm_data_regression.yml

CISDP-3212 updating infection type string

---

cishouseholds/pipeline/timestamp_map.py
dummy_data_generation/schemas.py
tests/derive/test_assign_survey_completed_status.py

CISDP-3197 - update survey_completed_datetime implementation

---

cishouseholds/phm/json_decode.py

3212 - condition to handle feedback items in batched json

---

cishouseholds/derive.py
cishouseholds/pipeline/version_specific_processing/phm_transformations.py
tests/derive/test_assign_date_from_filename.py
tests/pipeline/test_survey_responses_version_phm/processed_responses_phm_data_regression.yml
tests/pipeline/test_survey_responses_version_phm/processed_responses_phm_schema_regression.yml

3196 - assigned file_date column from json

---

cishouseholds/pipeline/mapping.py
cishouseholds/pipeline/validation_schema.py
dummy_data_generation/schemas.py
tests/pipeline/test_survey_responses_version_phm/processed_responses_phm_data_regression.yml
tests/pipeline/test_survey_responses_version_phm/processed_responses_phm_schema_regression.yml

3215 - added schema_name to validation_schema

---

cishouseholds/derive.py
cishouseholds/pipeline/load.py
cishouseholds/pipeline/pipeline_stages.py

CISDP- 3194 update to check_table_exists with latest_table param

---

cishouseholds/phm/reporting_class.py
cishouseholds/pipeline/pipeline_stages.py
cishouseholds/validate.py

3210 - update phm MI and validation report stages

---

cishouseholds/pipeline/lookup_and_regex_transformations.py
cishouseholds/pipeline/pipeline_stages.py
cishouseholds/pipeline/version_specific_processing/participant_extract_phm.py

3210 - fix MI implementation and participant_extract join

---

cishouseholds/pipeline/pipeline_stages.py

3231 - add handling for no column_name_map param

---

cishouseholds/pipeline/lookup_and_regex_transformations.py
cishouseholds/pipeline/pipeline_stages.py

3220 - add transformation for joining geography cols

---

cishouseholds/pipeline/pipeline_stages.py
cishouseholds/pipeline/version_specific_processing/phm_transformations.py
cishouseholds/pipeline/visit_transformations.py
tests/pipeline/test_survey_responses_version_phm/processed_responses_phm_data_regression.yml
tests/pipeline/test_survey_responses_version_phm/processed_responses_phm_schema_regression.yml

CISDP-3221/3229 adding visit based derivations to phm transformations

---

cishouseholds/pipeline/lookup_and_regex_transformations.py
cishouseholds/pipeline/pipeline_stages.py

Cisdp 3235 - creating subset of valid_survey_responses

---

cishouseholds/pipeline/demographic_transformations.py
cishouseholds/pipeline/pipeline_stages.py

3219 - update demographic_transformations for phm

---

cishouseholds/pipeline/version_specific_processing/phm_transformations.py
tests/pipeline/test_survey_responses_version_phm/processed_responses_phm_data_regression.yml
tests/pipeline/test_survey_responses_version_phm/processed_responses_phm_schema_regression.yml

3234 - derived visit_date from visit_datetime in phm_transformations

---

cishouseholds/pipeline/demographic_transformations.py
cishouseholds/pipeline/job_transformations.py
cishouseholds/pipeline/lookup_and_regex_transformations.py
cishouseholds/pipeline/pipeline_stages.py
cishouseholds/pipeline/visit_transformations.py

CISDP- 3238 updates for demographic and visit transformations

---

cishouseholds/pipeline/lookup_and_regex_transformations.py
cishouseholds/pipeline/pipeline_stages.py

CISDP 3238 v2 - demographic transformation stage tweaking

---

cishouseholds/pipeline/demographic_transformations.py
cishouseholds/pipeline/lookup_and_regex_transformations.py

CISDP-3239 fill forward hh count from CIS, derive count group

---

cishouseholds/filter.py
cishouseholds/pipeline/version_specific_processing/phm_transformations.py
tests/filter/test_filter_exclude_by_pattern.py

3214 - added function to filter by pattern

---

cishouseholds/pipeline/mapping.py
cishouseholds/pipeline/pipeline_stages.py

Added filter_dataframe stage so that you can filter before / after any stage required
Removed survey_completion_status_flushed from mapping.py which caused issues in validate_survey_responses
Added 'Do not know' to yes_no_unknown' categories in lieu of aligning all responses of this type to a singe categorical value

CISDP-3253 new stage to filter dataframe for optional vars

---

cishouseholds/pipeline/input_file_processing.py
cishouseholds/pipeline/validation_calls.py

CISDP-3256 update input deduplication and output validation following uat testing

---

cishouseholds/pipeline/run.py

CISDP 3260 - fixing checkpoint folder clear up

---

cishouseholds/pipeline/input_file_processing.py
cishouseholds/pipeline/input_file_stages.py
cishouseholds/pipeline/logging.py
cishouseholds/pipeline/pipeline_stages.py

Cisdp 3261 fix: fixing validation for survey table comparisons

---

cishouseholds/pipeline/load.py

CISDP-3091 - fix delete_tables function logic
